### ISSUE TITLE
Show plugins folder button text changed

### ISSUE THREAD

**Issue by tadomaitis** [getomni/insomnia-omni#3]
As for Insomnia-core version 2020.4.0 (Linux Manjaro, at least), the button to open Plugins Folder is now labeled "Reveal Plugins Folder" instead of former "Show plugins folder". Besides that, the opened folder is the parent folder to the plugins folder itself.

**Comment by jpedroschmitz** [comment]
Thanks for this issue, we have updated our install instructions on #4!
